### PR TITLE
update timeouts to give examples in Golang durations

### PR DESCRIPTION
**Pull request by willaaam**
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Derek set title: update timeouts to give examples in Golang durations

**Comment by alexellis** [comment]
All timeout values need to be specified in Golang durations. Please feel free to use community support if you get stuck in the future :-)

https://docs.openfaas.com/community

No question too small to be asked there. 

Out of curiosity what were you attempting to do? 

Alex

**Comment by alexellis** [comment]
Please can you run `git commit -s --amend` and repush? 

The usecase sounds really interesting. Speak on slack?

Alex

**Comment by willaaam** [comment]
I kind of did everything via the github website as it was a quicky - I you know how I'd be happy to help :). I'll join slack in an hour or so!

**Comment by alexellis** [comment]
Oh dear that didn't go very well. We can't accept the merge commit. Just use git reset and push it up again or let me know if you want me to do the git piece.

**Comment by alexellis** [comment]
Thanks for your patience!

**Pull request closed without merging**
