### PR TITLE
Update ISSUE_TEMPLATE.md

### PR DESCRIPTION
**Pull request by cody3337**
## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by burtonr** [comment]
@cody3337 There is no description in your Pull Request, and you have not signed your commit(s). Please read the [contribution guide](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) before submitting your work.

Also, I will close this as the change is not correct. The spelling is the correct spelling of the word. Your change changes it to the US variant. Please see the definition provided by Oxford Dictionary: https://en.oxforddictionaries.com/definition/behaviour

If you'd like to join our Slack community to see other areas where you could make an impacting change, please see the [docs](https://docs.openfaas.com/community/#slack-workspace)

**Comment by burtonr** [comment]
Derek: close

**Comment by burtonr** [comment]
Derek close

**Comment by alexellis** [comment]
Derek add label: invalid

**Comment by alexellis** [comment]
Thanks Burton

**Pull request closed without merging**
