### PR TITLE
Propagate Host header from incoming request to the function.

### PR DESCRIPTION
**Pull request by dmrub**
Host HTTP header was not propagated to the function because it is not
a part of http.Request.Header map.

Signed-off-by: Dmitri Rubinstein <dmitri.rubinstein@googlemail.com>

## Motivation and Context

- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by ivanayov** [comment]
Thanks @dmrub 

Can you please try to run `./build.sh` locally as the build fails?

**Comment by dmrub** [comment]
I used ./build.sh when modifying and testing and it worked, can you send me
your stdout/stderr output ?

Ivana Yovcheva <notifications@github.com> schrieb am Fr., 10. Aug. 2018,
16:49:

**Comment by alexellis** [comment]
I'm seeing some odd errors in the build log (linked on the button that says Details)

https://travis-ci.org/openfaas-incubator/of-watchdog/builds/414527953?utm_source=github_status&utm_medium=notification

**Comment by dmrub** [comment]
I was not able to reproduce an error but there was bug in the Travis CI configuration and build.sh script, which I fixed: https://github.com/dmrub/of-watchdog/commit/bd702157a0c7793af05a78bd05350beaaf38efb3
It builds now.

**Comment by alexellis** [comment]
Hi please can you expand on why the value "language: minimal" was added to the build for Travis?

Was something broken and subsequently fixed?

Alex

**Comment by alexellis** [comment]
Looks good, but I have an outstanding question on the Travis update.

Please could you raise a similar PR to openfaas/faas?

Thanks,

Alex

**Comment by alexellis** [comment]
Please can you also follow-up with a couple of unit tests in a new Pull Request that show the behavior?

**Comment by dmrub** [comment]
About value "language: minimal" that I added to Travis: This was not a fix, but an improvement since Travis, when no language is specified, uses Ruby by default. And because of-watchdog require only docker for building I changed language to minimal for reducing build time.

**Comment by alexellis** [comment]
Thanks for explaining.. I like that 👍 Maybe it would work for our other repos too?

**Pull request merged**
